repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.1
    hooks:
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: [--fix, --exit-non-zero-on-fix, --exclude, ./pyproject.toml, --exclude, ./tests/*, ./src, ./notebooks]
