version: "3.8"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - PLAYLIST_SELECTION_CLIENT_ID=${PLAYLIST_SELECTION_CLIENT_ID}
      - PLAYLIST_SELECTION_CLIENT_SECRET=${PLAYLIST_SELECTION_CLIENT_SECRET}
      - PLAYLIST_SELECTION_CALLBACK_URL=${PLAYLIST_SELECTION_CALLBACK_URL}
      - PLAYLIST_SELECTION_S3_BUCKET_NAME=${PLAYLIST_SELECTION_S3_BUCKET_NAME}
      - PLAYLIST_SELECTION_S3_PROFILE_NAME=${PLAYLIST_SELECTION_S3_PROFILE_NAME}
      - PLAYLIST_SELECTION_MODEL_CLASS=${PLAYLIST_SELECTION_MODEL_CLASS}
      - PLAYLIST_SELECTION_MODEL_NAME=${PLAYLIST_SELECTION_MODEL_NAME}
    volumes:
      - .aws/:/root/.aws:ro

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
