[project]
requires-python = ">=3.10"

[tool.poetry]
name = "project"
version = "0.1.0"
description = ""
authors = ["Vyacheslav Kostrov <slavkostrov@gmail.com>"]
readme = "README.md"
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.test.dependencies]
pytest = "^7.3.1"

[tool.poetry.group.dev.dependencies]
ruff = "0.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120
extend-select = [
  "E501",
  "UP",  # pyupgrade
  "D",   # pydocstyle
]
extend-exclude = [
    "tests/*.py",
]
force-exclude = true

[tool.ruff.pydocstyle]
convention = "google"
