[project]
requires-python = ">=3.10"

[tool.ruff]
extend-select = ["E501"]
line-length = 120

[tool.ruff]
extend-select = [
  "UP",  # pyupgrade
  "D",   # pydocstyle
]

[tool.ruff.pydocstyle]
convention = "google"
