"""[ADD] remove song_id from playlist_table

Revision ID: e63fcefc9099
Revises: f5ec1c5dba2d
Create Date: 2024-03-13 09:12:58.869845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e63fcefc9099'
down_revision: Union[str, None] = 'f5ec1c5dba2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('playlist_song_id_fkey', 'playlist', type_='foreignkey')
    op.drop_column('playlist', 'song_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlist', sa.Column('song_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('playlist_song_id_fkey', 'playlist', 'song', ['song_id'], ['id'])
    # ### end Alembic commands ###
