"""[ADD] status column for request

Revision ID: 9cab6df657b5
Revises: 328cf8380bc7
Create Date: 2024-03-12 21:25:35.610883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9cab6df657b5'
down_revision: Union[str, None] = '328cf8380bc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PENDING', 'RECEIVED', 'COMPLETED', name='status').create(op.get_bind())
    op.add_column('request', sa.Column('status', postgresql.ENUM('PENDING', 'RECEIVED', 'COMPLETED', name='status', create_type=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'status')
    sa.Enum('PENDING', 'RECEIVED', 'COMPLETED', name='status').drop(op.get_bind())
    # ### end Alembic commands ###
