"""cascade

Revision ID: c3b1a1cc9614
Revises: 051455260a4d
Create Date: 2024-03-17 17:28:03.987239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3b1a1cc9614'
down_revision: Union[str, None] = '051455260a4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('request_user_uid_fkey', 'request', type_='foreignkey')
    op.create_foreign_key(op.f('request_user_uid_fkey'), 'request', 'user', ['user_uid'], ['uid'], onupdate='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('request_user_uid_fkey'), 'request', type_='foreignkey')
    op.create_foreign_key('request_user_uid_fkey', 'request', 'user', ['user_uid'], ['uid'])
    # ### end Alembic commands ###
