"""optional user_uid

Revision ID: 945061111b07
Revises: 76edded3a5b6
Create Date: 2024-03-17 12:18:41.995127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '945061111b07'
down_revision: Union[str, None] = '76edded3a5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('request', 'user_uid',
               existing_type=sa.UUID(),
               nullable=True)
    op.sync_enum_values('public', 'status', ['PENDING', 'RECEIVED', 'COMPLETED', 'PROCESSING', 'FAILED'],
                        [TableReference(table_schema='public', table_name='request', column_name='status')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'status', ['PENDING', 'RECEIVED', 'COMPLETED', 'FAILED', 'PROCESSING'],
                        [TableReference(table_schema='public', table_name='request', column_name='status')],
                        enum_values_to_rename=[])
    op.alter_column('request', 'user_uid',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
