"""[ADD] association_table

Revision ID: f5ec1c5dba2d
Revises: 9cab6df657b5
Create Date: 2024-03-12 21:32:27.648121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5ec1c5dba2d'
down_revision: Union[str, None] = '9cab6df657b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlist_to_song',
    sa.Column('playlist', sa.Uuid(), nullable=True),
    sa.Column('song', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['playlist'], ['playlist.uid'], name=op.f('playlist_to_song_playlist_fkey')),
    sa.ForeignKeyConstraint(['song'], ['song.id'], name=op.f('playlist_to_song_song_fkey'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playlist_to_song')
    # ### end Alembic commands ###
