"""Ini[ADD] link column

Revision ID: 90f6b4cf9953
Revises: e63fcefc9099
Create Date: 2024-03-16 10:30:00.965310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90f6b4cf9953'
down_revision: Union[str, None] = 'e63fcefc9099'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('link', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('song', 'link')
    # ### end Alembic commands ###
