"""tinitial

Revision ID: 051455260a4d
Revises:
Create Date: 2024-03-17 17:16:00.770057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '051455260a4d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PENDING', 'RECEIVED', 'COMPLETED', 'PROCESSING', 'FAILED', name='status').create(op.get_bind())
    op.create_table('playlist',
    sa.Column('uid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid', name=op.f('playlist_pkey'))
    )
    op.create_table('song',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('artist_name', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('song_pkey'))
    )
    op.create_table('user',
    sa.Column('uid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('spotify_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid', name=op.f('user_pkey')),
    sa.UniqueConstraint('spotify_id', name=op.f('user_spotify_id_key'))
    )
    op.create_table('playlist_to_song',
    sa.Column('playlist', sa.Uuid(), nullable=True),
    sa.Column('song', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['playlist'], ['playlist.uid'], name=op.f('playlist_to_song_playlist_fkey')),
    sa.ForeignKeyConstraint(['song'], ['song.id'], name=op.f('playlist_to_song_song_fkey'))
    )
    op.create_table('request',
    sa.Column('uid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'RECEIVED', 'COMPLETED', 'PROCESSING', 'FAILED', name='status', create_type=False), nullable=False),
    sa.Column('user_uid', sa.Uuid(), nullable=True),
    sa.Column('playlist_uid', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['playlist_uid'], ['playlist.uid'], name=op.f('request_playlist_uid_fkey')),
    sa.ForeignKeyConstraint(['user_uid'], ['user.uid'], name=op.f('request_user_uid_fkey')),
    sa.PrimaryKeyConstraint('uid', name=op.f('request_pkey'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request')
    op.drop_table('playlist_to_song')
    op.drop_table('user')
    op.drop_table('song')
    op.drop_table('playlist')
    sa.Enum('PENDING', 'RECEIVED', 'COMPLETED', 'PROCESSING', 'FAILED', name='status').drop(op.get_bind())
    # ### end Alembic commands ###
