"""[ADD] status column for request

Revision ID: 302be0f15b05
Revises: 328cf8380bc7
Create Date: 2024-03-12 21:05:12.147212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '302be0f15b05'
down_revision: Union[str, None] = '328cf8380bc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('status', sa.Enum('PENDING', 'RECEIVED', 'COMPLETED', name='status'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'status')
    # ### end Alembic commands ###
