"""Initial migration

Revision ID: 210abb607a0d
Revises:
Create Date: 2024-03-12 20:13:08.861255

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '210abb607a0d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlist',
    sa.Column('uid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('uid', name=op.f('playlist_pkey'))
    )
    op.create_table('song',
    sa.Column('uid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('spotify_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('uid', name=op.f('song_pkey'))
    )
    op.create_table('user',
    sa.Column('uid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('spotify_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('uid', name=op.f('user_pkey')),
    sa.UniqueConstraint('spotify_id', name=op.f('user_spotify_id_key'))
    )
    op.create_table('request',
    sa.Column('uid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_uid', sa.Uuid(), nullable=False),
    sa.Column('playlist_uid', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['playlist_uid'], ['playlist.uid'], name=op.f('request_playlist_uid_fkey')),
    sa.ForeignKeyConstraint(['user_uid'], ['user.uid'], name=op.f('request_user_uid_fkey')),
    sa.PrimaryKeyConstraint('uid', name=op.f('request_pkey'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request')
    op.drop_table('user')
    op.drop_table('song')
    op.drop_table('playlist')
    # ### end Alembic commands ###
