on:
    push:
      branches: [ "autodeploy" ]

jobs:
    update-yc:
        runs-on: ubuntu-latest
        steps:
            - name: Login to Yandex Cloud Container Registry
              id: login-cr
              uses: yc-actions/yc-cr-login@v1
              with:
                  yc-sa-json-credentials: '${{ secrets.YC_SA_JSON_CREDENTIALS }}'
            - name: Checkout
              uses: actions/checkout@v2
            - name: 'Build, tag, and push image to Yandex Cloud Container Registry'
              env:
                  CR_REGISTRY: '${{ secrets.CR_REGISTRY }}'
                  CR_REPOSITORY: playlist-selection
                  IMAGE_TAG: latest # '${{ github.sha }}'
              run: |
                  docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .
                  docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG
            - name: Deploy COI VM
              id: deploy-coi
              uses: yc-actions/yc-coi-deploy@v2
              env:
                  CR_REGISTRY: '${{ secrets.CR_REGISTRY }}'
                  CR_REPOSITORY: playlist-selection
                  IMAGE_TAG: latest # '${{ github.sha }}'
              with:
                  yc-sa-json-credentials: '${{ secrets.VM_YC_SA_JSON_CREDENTIALS }}'
                  folder-id: '${{ secrets.FOLDER_ID }}'
                  vm-name: playlist-selection
                  vm-service-account-id: '${{ secrets.SERVICE_ACCOUNT_ID }}'
                  vm-cores: 2
                  vm-memory: 2Gb
                  vm-core-fraction: 20
                  vm-subnet-id: '${{ secrets.SUBNET_ID }}'
                  user-data-path: ./user-data.yaml
                  docker-compose-path: ./docker-compose.yaml
