on:
    push:
      branches: [ "autodeploy" ]

jobs:
    update-yc:
        runs-on: ubuntu-latest
        steps:
            - name: Login to Yandex Cloud Container Registry
              id: login-cr
              uses: yc-actions/yc-cr-login@v1
              with:
                  yc-sa-json-credentials: '${{ secrets.YC_SA_JSON_CREDENTIALS }}'
            - name: 'Build, tag, and push image to Yandex Cloud Container Registry'
              env:
                  CR_REGISTRY: '${{ secrets.CR_REGISTRY }}'
                  CR_REPOSITORY: playlist-selection
                  IMAGE_TAG: '${{ github.sha }}'
              run: |
                  pwd
                  ls
                  docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG /home/runner/work/playlist_selection/playlist_selection
                  docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG
            # - name: Deploy COI VM
            #   id: deploy-coi
            #   uses: yc-actions/yc-coi-deploy@v2
            #   env:
            #       CR_REGISTRY: crp00000000000000000
            #       CR_REPOSITORY: my-cr-repo
            #       IMAGE_TAG: '${{ github.sha }}'
            #   with:
            #       yc-sa-json-credentials: '${{ secrets.YC_SA_JSON_CREDENTIALS }}'
            #       folder-id: bbajn5q2d74c********
            #       vm-name: yc-action-demo
            #       vm-service-account-id: ajeqnasj95o7********
            #       vm-cores: 2
            #       vm-memory: 2Gb
            #       vm-core-fraction: 100
            #       vm-subnet-id: e9b*********
            #       user-data-path: ./user-data.yaml
            #       docker-compose-path: ./docker-compose.yaml
