name: Pull Request
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Black
        uses: microsoft/action-python@0.7.0
        with:
          black: true
          workdir: .
          python_version: 3.10

      - name: Pylint
        uses: microsoft/action-python@0.7.0
        with:
          pylint: true
          workdir: .
          python_version: 3.10
          
      - name: Flake8
        uses: microsoft/action-python@0.7.0
        with:          
          flake8: true
          workdir: .
          python_version: 3.10

  testing:
    runs-on: ubuntu-latest
    steps:    
      - name: Pytest
        uses: microsoft/action-python@0.7.0
        with:          
          testing: true
          python_version: 3.10
