name: Deploy
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Login to Yandex Cloud Container Registry
          id: login-cr
          uses: yc-actions/yc-cr-login@v1
          with:
              yc-sa-json-credentials: '${{ secrets.YC_SA_JSON_CREDENTIALS }}'
        - name: Install yc cli and login into yandex cloud
          uses: okar1/yc-cli-install@master
          with:
            SA_KEY: '${{ secrets.YC_SA_JSON_CREDENTIALS }}'
        - name: Checkout
          uses: actions/checkout@v2
        - name: Deploy COI VM
          run: yc compute instance start playlist-selection-baseline
