name: Deploy
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Login to Yandex Cloud Container Registry
          id: login-cr
          uses: yc-actions/yc-cr-login@v1
          with:
              yc-sa-json-credentials: '${{ secrets.VM_YC_SA_JSON_CREDENTIALS  }}'
        - name: Install yc cli and login into yandex cloud
          uses: okar1/yc-cli-install@master
          with:
            SA_KEY: '${{ secrets.VM_YC_SA_JSON_CREDENTIALS  }}'
        - name: Checkout
          uses: actions/checkout@v2
        - name: Deploy COI VM
          run: yc compute instance start epdr1jt20hvabffcjkee
          continue-on-error: true
        - name: multiple command
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.PASSWORD }}
            port: 22
            script: |
              whoami
              ls -al
